insert into job_posting
(title, company, company_email, location_type, city, seniority, contract_type, salary_range, description, requirements, apply_url, status, views, created_at, updated_at)
values
('Desenvolvedor Java Spring', 'Nuvem Sertao', 'talentos@nuvemsertao.dev', 'REMOTE', null, 'MID_LEVEL', 'PJ', 'R$ 7.000 - R$ 10.000', 'Atuacao em produto SaaS com Java, Spring Boot, PostgreSQL e integracoes REST. Time distribuido, rotina leve e foco em entrega continua.', 'Java 21, Spring Boot, JPA, PostgreSQL, Docker e boas praticas de testes.', 'https://example.com/vaga-java', 'PUBLISHED', 18, now() - interval '5 days', now() - interval '5 days'),
('Frontend React', 'Mangaba Labs', 'jobs@mangabalabs.com', 'REMOTE', null, 'JUNIOR', 'CLT', 'R$ 4.000 - R$ 6.000', 'Vaga para construir interfaces responsivas para produtos digitais usados por clientes no Brasil inteiro.', 'React, TypeScript, HTML semantico, CSS moderno e atencao a acessibilidade.', null, 'PUBLISHED', 11, now() - interval '4 days', now() - interval '4 days'),
('Analista de Dados', 'Data PB', 'rh@datapb.com.br', 'PRESENTIAL_PB', 'Joao Pessoa', 'MID_LEVEL', 'CLT', 'R$ 5.500 - R$ 8.000', 'Trabalho presencial em Joao Pessoa com analise de indicadores, modelagem de dados e dashboards para areas de negocio.', 'SQL, Python, Power BI, pensamento analitico e comunicacao clara.', null, 'PUBLISHED', 22, now() - interval '3 days', now() - interval '3 days'),
('QA Automation', 'Borborema Tech', 'carreiras@borborematech.com', 'PRESENTIAL_PB', 'Campina Grande', 'SENIOR', 'CLT', 'R$ 8.000 - R$ 11.000', 'Vaga presencial em Campina Grande para estruturar automacao de testes, qualidade de release e cultura de confiabilidade.', 'Cypress ou Playwright, testes de API, CI/CD e experiencia guiando times.', null, 'PUBLISHED', 15, now() - interval '2 days', now() - interval '2 days'),
('DevOps Engineer', 'Atlas Cloud', 'people@atlascloud.dev', 'REMOTE', null, 'SENIOR', 'PJ', 'R$ 12.000 - R$ 16.000', 'Atuacao remota em infraestrutura cloud, observabilidade, pipelines e plataformas internas para times de engenharia.', 'Docker, Linux, GitHub Actions, PostgreSQL, logs, metricas e seguranca operacional.', 'https://example.com/devops', 'PUBLISHED', 27, now() - interval '1 day', now() - interval '1 day'),
('Estagio em Desenvolvimento', 'Litoral Software', 'estagios@litoralsoftware.com', 'PRESENTIAL_PB', 'Joao Pessoa', 'INTERNSHIP', 'INTERNSHIP', 'R$ 1.200 + beneficios', 'Oportunidade para estudantes aprenderem desenvolvimento web, versionamento, testes e entrega de software em equipe.', 'Logica de programacao, Git, HTML, CSS e vontade de aprender.', null, 'PENDING', 3, now(), now());
