delete from job_posting
where company in (
    'Nuvem Sertao',
    'Mangaba Labs',
    'Data PB',
    'Borborema Tech',
    'Atlas Cloud',
    'Litoral Software'
);

insert into job_posting
(title, company, company_email, location_type, city, seniority, contract_type, salary_range, description, requirements, apply_url, status, views, created_at, updated_at)
values
('Pessoa Desenvolvedora Full Stack Junior', 'Zenvia', 'curadoria@radartechpb.dev', 'REMOTE', null, 'JUNIOR', 'CLT', 'Nao informado', 'Vaga remota para desenvolvimento full stack com foco em front-end, produto e evolucao profissional em time de tecnologia.', 'Vue, React, Node.js, SQL ou NoSQL, testes automatizados e boas praticas de desenvolvimento.', 'https://zenvia.gupy.io/job/eyJqb2JJZCI6MTEwNDc4NTUsInNvdXJjZSI6Imd1cHlfcG9ydGFsIn0%3D?jobBoardSource=gupy_portal', 'PUBLISHED', 31, now() - interval '8 days', now() - interval '8 days'),
('Software Developer Junior - .NET', 'Localiza', 'curadoria@radartechpb.dev', 'REMOTE', null, 'JUNIOR', 'CLT', 'Nao informado', 'Oportunidade remota para atuar em desenvolvimento de servicos em plataforma .NET, APIs e manutencao de solucoes digitais.', '.NET, APIs, boas praticas de engenharia, colaboracao em time e vontade de aprender.', 'https://localiza.gupy.io/jobs/7379530?jobBoardSource=gupy_public_page', 'PUBLISHED', 28, now() - interval '7 days', now() - interval '7 days'),
('Estagio em Desenvolvimento de Software', 'EdTech via WeRecruiter', 'curadoria@radartechpb.dev', 'REMOTE', null, 'INTERNSHIP', 'INTERNSHIP', 'Nao informado', 'Estagio para estudantes participarem do desenvolvimento e manutencao de sistemas web e plataformas educacionais.', 'Cursando Computacao, ADS ou areas afins. Desejavel Python, Node.js, React, TypeScript, API REST ou HTML/CSS.', 'https://werecruiter.gupy.io/jobs/10819816', 'PUBLISHED', 24, now() - interval '6 days', now() - interval '6 days'),
('Estagiario de Tecnologia da Informacao', 'ENGINEERING DO BRASIL S/A', 'curadoria@radartechpb.dev', 'REMOTE', null, 'INTERNSHIP', 'INTERNSHIP', 'R$ 2.339 - R$ 2.982', 'Estagio remoto para apoio em desenvolvimento, testes e manutencao de solucoes de software.', 'Interesse em desenvolvimento, testes de software, integracoes e aprendizado em rotina tecnica.', 'https://br.indeed.com/viewjob?jk=d85c56ed0e7da0b0', 'PUBLISHED', 21, now() - interval '5 days', now() - interval '5 days'),
('Estagio em Automacao e Desenvolvimento', 'Liber', 'curadoria@radartechpb.dev', 'REMOTE', null, 'INTERNSHIP', 'INTERNSHIP', 'Nao informado', 'Vaga remota para apoiar automacoes, integracoes e scripts em uma area de tecnologia e operacoes.', 'Conhecimento basico em Python, interesse em automacao, N8N, IA, organizacao e trabalho em equipe.', 'https://br.indeed.com/viewjob?jk=ae3114e1710aa198', 'PUBLISHED', 19, now() - interval '4 days', now() - interval '4 days'),
('Estagio em Desenvolvimento de Sistemas - 100% Remoto', 'Empresa Confidencial', 'curadoria@radartechpb.dev', 'REMOTE', null, 'INTERNSHIP', 'INTERNSHIP', 'Nao informado', 'Oportunidade 100% remota para apoio no ciclo de desenvolvimento de software e evolucao de sistemas.', 'Logica de programacao, fundamentos de desenvolvimento web, Git e vontade de aprender em equipe.', 'https://br.linkedin.com/jobs/view/est%C3%A1gio-em-desenvolvimento-de-sistemas-home-office-at-empresa-confidencial-4421333989?pageNum=0&position=26', 'PUBLISHED', 17, now() - interval '3 days', now() - interval '3 days'),
('Auxiliar de TI', 'Sistema Almanaque Plataforma e Treinamento Profissional', 'curadoria@radartechpb.dev', 'PRESENTIAL_PB', 'Joao Pessoa', 'JUNIOR', 'CLT', 'R$ 1.621 - R$ 1.800', 'Vaga presencial em Joao Pessoa para suporte tecnico interno, manutencao de equipamentos e apoio a infraestrutura.', 'Manutencao de computadores, redes, impressoras, organizacao de chamados e boa comunicacao.', 'https://br.indeed.com/viewjob?jk=594629f9b3585037', 'PUBLISHED', 15, now() - interval '2 days', now() - interval '2 days'),
('Policia Federal - Estagio em TI / Computacao', 'Mais Estagios', 'curadoria@radartechpb.dev', 'PRESENTIAL_PB', 'Joao Pessoa', 'INTERNSHIP', 'INTERNSHIP', 'Nao informado', 'Estagio presencial em Joao Pessoa com apoio em atividades tecnicas, gestao de documentos e procedimentos de informatica.', 'Estar a partir do segundo periodo e ter interesse em computacao, suporte e rotina tecnica.', 'https://br.indeed.com/viewjob?jk=c00f579b096f4229', 'PUBLISHED', 14, now() - interval '1 day', now() - interval '1 day');
